DECLARE @Query VARCHAR(MAX), @ANIO VARCHAR(10),@MES VARCHAR(10),@DIA INT
SET @ANIO = DATEPART(YY,GETDATE()-1)
SET @MES = RIGHT('0' + RTRIM(DATEPART(MM,GETDATE()-1)),2)
SET @DIA = 5
	
	IF(SELECT DATEPART(DD,GETDATE())) > @DIA
		
		BEGIN

			SET @Query = 
				'
				SELECT '+@ANIO+''+@MES+'
				'
			EXEC(@Query)
		END
	ELSE 
		BEGIN
			PRINT 'NO SE CUMPLE CONDICION'
		END