--Da automaticamente el MES_ACTUAL y MES_ANTERIOR

DECLARE @MES_ACTUAL VARCHAR(10),@MES_ANTERIOR VARCHAR(10)

SET @MES_ACTUAL = (SELECT (CASE MONTH (GETDATE())
	WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' 
	WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' 
	WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SEPTIEMBRE' 
	WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' 
	END) +RIGHT(CAST(YEAR(GETDATE()) AS VARCHAR), 2))

PRINT @MES_ACTUAL

SET @MES_ANTERIOR = (SELECT (CASE MONTH (DATEADD(MM,-1,GETDATE()))
	WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' 
	WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' 
	WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SEPTIEMBRE' 
	WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' 
	END) +RIGHT(CAST(YEAR(DATEADD(MM,-1,GETDATE())) AS VARCHAR), 2))

PRINT @MES_ANTERIOR