USE DB_PRUEBAS

CREATE VIEW VW_MONITOREO_OBJETOS_BBDD

AS 
(
	SELECT o.[NAME] AS NOMBRE_OBJ,
	o.[TYPE_DESC] AS TIPO_OBJ,
	o.CREATE_DATE AS FECHA_CREACION,
	o.MODIFY_DATE AS FECHA_MODIFICACION,
	SUM(a.used_pages)*8 AS 'SIZE_KB'
	FROM SYS.OBJECTS o
	LEFT JOIN SYS.INDEXES i ON o.OBJECT_ID = i.OBJECT_ID
	LEFT JOIN SYS.PARTITIONS  p ON i.OBJECT_ID = p.OBJECT_ID AND i.index_id = p.index_id
	LEFT JOIN SYS.ALLOCATION_UNITS a ON p.partition_id = a.container_id
	WHERE o.[TYPE_DESC] NOT IN ('SYSTEM_TABLE','SERVICE_QUEUE','INTERNAL_TABLE')
	GROUP BY o.[NAME],o.[TYPE_DESC],o.CREATE_DATE ,o.MODIFY_DATE 
)
------------------------------------------------------------------------
GO

SELECT * FROM VW_MONITOREO_OBJETOS_BBDD
ORDER BY TIPO_OBJ